### ISSUE TITLE
`evaluate-contigs` fails with `OSError: [Errno 28] No space left on device`

### ISSUE THREAD

**Issue by gregcaporaso** [bokulich-lab/q2-assembly#39] opened 2023-02-21 15:32 UTC
On two separate machines (both HPC clusters), I've had `evaluate-contigs` fail due to available disk space. I can see from the log that it downloads a lot of files. @misialq, have you run into this? Any ideas on how to address this? I haven't actually got this command to complete yet, after testing on two different studies (and two different systems, as I mentioned). Let me know if you'd like the error log - I can send that by email.

**Comment by misialq** [comment] 2023-02-21 16:08
Hey @gregcaporaso, I suspect this is related to https://github.com/bokulich-lab/q2-assembly/issues/35 - QUAST is downloading some reference data in the background (which I realised only recently) so we need to make it possible to just provide those as input to the action itself (I haven't checked in detail whether that's possible or not but I certainly hope it is). Please do send the log file over, if you have it - I can have a look just to confirm whether it's this problem or something else entirely. Thanks!

**Comment by gregcaporaso** [comment] 2023-02-21 19:54
I thought it might be related to #35 too - just sent you the error log by email.

**Comment by colinvwood** [comment] 2023-04-12 23:13
Any updates? We ran into the same error today when using a tiny (4 sample) dataset.

**Comment by gregcaporaso** [comment] 2023-04-13 00:25
> QUAST is downloading some reference data in the background (which I realised only recently) so we need to make it possible to just provide those as input to the action itself (I haven't checked in detail whether that's possible or not but I certainly hope it is).

It is possible - we can provide those in fasta format.

**Comment by colinvwood** [comment] 2023-04-13 16:52
It doesn't look like the space issue is due to downloaded references, but rather inefficiency in storing alignment files. See [this](https://github.com/ablab/quast/issues/123) and [this](https://github.com/ablab/quast/issues/106).

**Comment by misialq** [comment] 2023-04-14 08:38
Do you know whether you're running out space wherever the `tmp` directory is located or somewhere else? I think these are two separate issues: those alignment files should be stored in tmp (as far as I can tell) so if you're good on space there, the issue is somewhere else...

**Comment by colinvwood** [comment] 2023-04-17 22:46
I know that this is redundant to what I posted on the forum, but responding for reference's sake. I can confirm that the alignment files are being stored in the tmp directory, and can confirm that that directory did run out of space on our cluster after ~500GB had been written to it.

**Comment by misialq** [comment] 2024-04-11 09:22
I have not seen this happen with any of our runs so I'm going to close it for now (since we don't really have any way to address it on our end anyway)

**Closed by misialq** 2024-04-11 09:22 UTC
Labels: triage
