### ISSUE TITLE
BUG: action `assemble-megahit` does not allow for `--p-num-cpu-threads > 1`

### ISSUE THREAD

**Issue by Sann5** [bokulich-lab/q2-assembly#72] opened 2024-02-28 15:45 UTC
**Describe the bug**
It looks like one has to manually install megahit with `make` to disable `mpopcnt`, e.g. `make clean && make disablempopcnt=1` (but since megahit is installed through Conda I don't see how this could work). Otherwise one can only run on one CPU. See [this issue](https://github.com/voutcn/megahit/issues/40) in the megahit repo for more info. 

**To Reproduce**
1. Download data
```shell
cd <download_here>
wget https://www.polybox.ethz.ch/index.php/s/Zhk2igDBGRJTi1n/download
```
2. Run
```shell
qiime assembly assemble-megahit \
  --i-seqs reads.qza \
  --p-presets meta-sensitive \
  --p-num-cpu-threads 2 \
  --o-contigs contigs.qza \
  --verbose
```

**Expected error:**
```shell
Plugin error from assembly:

  An error was encountered while running MEGAHIT, (return code 245), please inspect stdout and stderr to learn more.
```

**Expected behavior**
Action works without errors. 

**Please complete the following information:**
 - OS: macOS
 - QIIME 2 version: 2024.5

**Comment by misialq** [comment] 2024-04-10 08:58
Hey @Sann5, I'm not sure what's up with this but I've definitely been able to use multiple cores on macOS. I tried with the dataset you linked - did not worked, but then I tried with another one of mine - all fine. Hence, I don't think the problem is inherent to the OS. How did you link it to the issue from your description? The error message there does not mention the same return code as yours. Moreover, that issue is with some ancient version of MEGAHIT from 9 years ago. I am about to close this issue, but wanted to check first if you had any other (new?) insight.

**Comment by Sann5** [comment] 2024-04-10 14:50
Hey Michal. I'm really confused. I think I might have been using another version because before I got an `Error occurs when assembling contigs for k=xxx [Exit code -4]` (which they say can be fixed by doing the installation via make) but now I get a different error. If you want I can investigate why it still does not work with this input and make another issue. In any case, I think we can close this one.

**Comment by misialq** [comment] 2024-04-10 16:34
Hey @Sann5, that's ok - I think we can close for now. Thanks!

**Closed** 2024-04-10 16:37 UTC
Labels: bug
